version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    env_file:
      .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    env_file:
      .env
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ${WORDPRESS_PUBLIC_HTML}:/var/www/html
      - ./wp_obsbiodiv_theme:/var/www/html/wp-content/themes/wp_obsbiodiv_theme
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
                /* Multisite */
                define('WP_ALLOW_MULTISITE', true);
                define('MULTISITE', true);
                define('SUBDOMAIN_INSTALL', false);
                define('DOMAIN_CURRENT_SITE', '${WORDPRESS_MAIN_DOMAIN}');
                define('PATH_CURRENT_SITE', '/');
                define('SITE_ID_CURRENT_SITE', 1);
                define('BLOG_ID_CURRENT_SITE', 1);
    working_dir: /var/www/html
